use_system_environment: true
use_sharding: false

# Variables
TOKEN: "Your Token here"
TGGTOKEN: "Your Top.gg Token here"
PREFIX: "Your Prefix here"
OWNERID: "Your Discord User ID here"

shard_count: 0
